### PR TITLE
Fix AMD issues.

### PR DESCRIPTION
**Pull request by rikkert**
Issues solved:
- Add a unit test for AMD loading.
- Remove the first (unnecessary) IIFE which causes a loading problem when used in a full AMD environment. (because the global jQuery is not defined yet)
- Plugins that depend on libraries that are not AMD modules (haml and handlebars) should use global objects.

### CODE REVIEW

**Comment by murat3** [comment]
+1
We need this patch too.

**Comment by smerik** [comment]
:+1:

**Comment by xixixao** [comment]
+1

**Comment by rikkert** [comment]
Added code review comments.

**Pull request merged**
