### PR TITLE
update haml to last version in order to support newest features...

### PR DESCRIPTION
**Pull request by mfo**
hope it helps :)

### CODE REVIEW

**Comment by alefnula** [comment]
+1 on this, this also solves the problem with firefox 5 and opera.

**Comment by pjg** [comment]
+1 on this. Maybe binding at least to [version 0.3.0](https://github.com/creationix/haml-js/commit/dcfea1066ed019) for now? Later commits were the breaking sort.

**Comment by mfo** [comment]
ok... i'll submit a new pull request on based on this commit. Thank for the suggestion ;)

**Comment by pjg** [comment]
@mfo also please read my comments at https://github.com/quirkey/sammy/pull/94 and https://github.com/creationix/haml-js/issues/43 :)

**Pull request closed without merging**
