### PR TITLE
update handlebars to the latest

### LINKED ISSUE #86: Handlebars Plugin Bug?
Hello,

I'm noticing a bug in the Handlebars plugin.
If I have a setup as follows,

```
var myvar = true;
var mylist = [1, 2, 3];

{{#mylist}}
  {{#../myvar}}true{{/../myvar}}
{{/mylist}}
```

output:

"true" will not be displayed.

However, the inverse works.

```
var myvar = false;
var mylist = [1, 2, 3];

{{#mylist}}
 {{^../myvar}}false{{/../myvar}}
{{/mylist}}
```

output: false false false

I thought that maybe it just wasn't recognizing the `../` notation for blocks.
But if I change `myvar = true` in the second example, then I again get no output.
So, clearly it is.

Also, I'm using the same template on the server side with express.js, hbs and handlebars,
and getting the expected behaviour. That's why I assume the problem is with the plugin. I haven't had time to debug it, maybe someone knows what's wrong.

Thanks.

### PR DESCRIPTION
**Pull request by arlolra**
This commit updates the Handlebars.js plugin to the latest version (1.0.0.beta.3).
It passes the qunit tests and fixes #86, as far as I can tell.

### CODE REVIEW

**Comment by Phunky** [comment]
Handlebars.registerHelper does not seem to be available unless i'm missing how to call it within Sammy.

**Comment by Phunky** [comment]
I've committed a fix for this, we just needed to expose Handlebars as a global.

**Comment by arlolra** [comment]
@Phunky I'm not sure they want to add Handlebars to `window`. It says [here](http://sammyjs.org/docs/plugins) that plugins shouldn't pollute the global scope.

So, I've added `Sammy.Handlebars.registerHelper` and, as requested in #70, `Sammy.Handlebars.SafeString`.

Again, please try it out and let me know. Thanks.

**Comment by Phunky** [comment]
D'oh, failed to read the docs there a couple of other Handlebar functions that may need to be exported.

**Comment by arlolra** [comment]
resolved in 0.7.0

**Pull request closed without merging**
