### PR TITLE
Add Hogan.js Templating Plugin

### PR DESCRIPTION
**Pull request by le0pard**
Add Hogan.js Templating Plugin.
Hogan.js site: http://twitter.github.com/hogan.js/

P.S. I run minify rake task, som many file looks like changed, it just changed "Built" date in files.

### CODE REVIEW

**Comment by le0pard** [comment]
how long it takes to check pull request?

**Comment by quirkey** [comment]
Sorry, for the long wait.

Can you resubmit with just the plugin and the tests? I can't merge it with the minified files as those need to only be generated with version bumps.

**Comment by le0pard** [comment]
Done.

**Comment by quirkey** [comment]
Thanks!

**Pull request merged**
