### PR TITLE
Events on and off, jQuery >= 1.7

### PR DESCRIPTION
**Pull request by jupapios**
live and die are deprecated and jquery 1.9 no longer supports them

### CODE REVIEW

**Comment by endor** [comment]
I think for now it makes sense to keep backward compatibility with delegate/undelegate. What do you think?

**Comment by dmr** [comment]
+1 to replace live and die with on and off.

https://github.com/jquery/jquery-migrate/

complains about my application because Sammy.js uses .live and .die

**Comment by endor** [comment]
As I said, it now uses delegate/undelegate instead of live/die. Does that solve your problem?

**Comment by dmr** [comment]
Yes, thank you!

**Comment by Azatey** [comment]
Could you please also update NuGet package with this fix?
Thank you.

**Comment by quirkey** [comment]
This was fixed with the backwards compatible `delegate` in master and now 0.7.3. Well move to `on` in the next release

**Pull request closed without merging**
