### PR TITLE
Made the plugins AMD enabled

### PR DESCRIPTION
**Pull request by delrosario**
Here's the formatted version of the plugins that can be loaded in amd style.

### CODE REVIEW

**Comment by rikkert** [comment]
@endor: can this be pulled in?
Changes to the plugins look ok to me.

**Comment by endor** [comment]
@rikkert I would like to merge this, but can you answer the question I asked before so I know what I am merging.

**Comment by delrosario** [comment]
For amd to work each plugins that sammy is using needs to be wrap in the amd module pattern and have the global variables set properly if amd is not being used.

(function (factory) {
  if (typeof define === 'function' && define.amd) {
    define(['jquery', 'sammy'], factory);
  } else {
    (window.Sammy = window.Sammy || {}).[PluginName] = factory(window.jQuery, window.Sammy); // set the plugin as a member of
  }
}(function ($, Sammy) {
  Sammy.[PluginName] = {}; // define our plugin.
  return Sammy.[PluginName]; // return a reference to our plugin.
}));

Right now only sammy can be loaded without the use of the shim config. And even if we use the shim config, some of the plugins, Sammy variable is not being defined properly.

You can see an example of this on my previous report. https://github.com/quirkey/sammy/issues/152

**Comment by rikkert** [comment]
That about sums it up.
But it doesn't explain why you added this to sammy.js:

``` javascript
return $.sammy = Sammy;
```

I think that it can be removed.

**Pull request merged**
