### PR TITLE
Correct issue 125 : mailto links break Sammy get()

### PR DESCRIPTION
**Pull request by tdetoux**
Hello,

This little commit corrects issue 125 : mailto links break Sammy get()
https://github.com/quirkey/sammy/issues/125

Note that in order to make the bug appears, you need not move to a mailto: url using the javascript way (window.location =) instead of using the standard href property.

The problem is that the onbeforeunload is triggered whenever the window.location is changed, whether it will cause a real page unload or not.

To solve this, I moved the Sammy unload function from the page's onbeforeunload to the onunload event, which is only triggered when the page is realy unloaded.

### CODE REVIEW

**Comment by quirkey** [comment]
Thanks so much for this - could not figure out what was going on.

**Comment by tdetoux** [comment]
You're welcome, that's what open source is all about.

**Comment by jpcartal** [comment]
Hi,

Just to let you know that this correction had a side effect on my code as I'm using modal windows and event.preventDefault(). As unload event can not be hidden with preventDefault(), my app is now stopping as soon as a modal window is closing.

Would it make sense to test the target of the event in the event handler ? In my case the target is HTMLDivElement when a popup modal window is closing, whereas my understanding is that sammy's unload event handler is targetting 
full window reload and/or manual url modification ?

Regards.

**Comment by tdetoux** [comment]
I was wondering : is this unload call realy necessary ? 
I mean, if we are navigating away from the page, won't the navigator flush all the javascript code and make the unload useless ?

**Comment by jpcartal** [comment]
Just a guess but this might be useful if you have to clean things up on server side when the application stops ?

**Comment by tdetoux** [comment]
Well, we are only talking about Sammy removing its listeners from the DOM here. The applications using Sammy can still bind to unload and do whatever they need.

**Pull request merged**
