### PR TITLE
Hoptoad and Exceptional plugins

### PR DESCRIPTION
**Pull request by jamesarosen**
Pulling this will resolve issue #75.

### CODE REVIEW

**Comment by quirkey** [comment]
Hey James

This looks awesome. Would you mind adding some basic inline docs? Really the very basics of what they do and maybe a quick requirements or install instructions since you need the hoptoad or exceptional gems in your app for this to work (right?).

thanks again,
--AQ

**Comment by jamesarosen** [comment]
I'd be happy to.

**Comment by jamesarosen** [comment]
Just added a couple commits that add docs and an optional implementation argument.

**Comment by quirkey** [comment]
Sweet. Looks awesome. Thanks James.

**Pull request closed without merging**
