### PR TITLE
underscore clash

### PR DESCRIPTION
**Pull request by dvv**
Hi! Please, consider replacing `_` in internal templating stuff with something more special, or famous underscore.js library gets broken

TIA,
--Vladimir

### CODE REVIEW

**Comment by jasondavies** [comment]
You might also want to consider using `_.noConflict()`: http://documentcloud.github.com/underscore/#noConflict

**Comment by dvv** [comment]
Sure. I presume, though, that `_` being an underscore.js is of way much use then a simple helper for sammy templates. Plus, some template-izers still make use of `p` which may clash local `p` variables, or such that come due to use of `with(){}` in template generator code.

Admit, that pure internally used vars should not interfere your code and not cause hardly caught bugs. No?

**Comment by jasondavies** [comment]
Agreed, yes. I didn't realise that these variables were leaking into templates and causing the clashes there. Carry on as you were :-)

**Comment by quirkey** [comment]
OK - So there are somethings that I want from this branch and somethings that I don't. I dont want to override jQuery core methods in any of the core methods. So I dont know about the changes to NestedParams and think there might have to be another way to do this. 

I do,however, want to pull in the template/var changes. If you can pull those into a branch of their own and get rid of the console.log statements (unsafe), I'll pull that in.

Thanks!

**Comment by dvv** [comment]
Cool. I'm not very fluent git user, though, and branches are mysterious to me. Couldn't you point out how to perform that? Shall I try to make a diff of your/my version of tmpl and submit that diff?

**Comment by dvv** [comment]
Please, consider applying https://gist.github.com/702013

TIA,
--Vladimir

**Comment by quirkey** [comment]
Pulled/Applied.

**Pull request closed without merging**
